sample_env = [['hilly', 'cave', 'forest', 'forest', 'forest', 'cave', 'forest', 'cave', 'flat', 'cave', 'flat', 'forest',
 'forest', 'cave', 'cave', 'hilly', 'hilly', 'hilly', 'cave', 'flat', 'hilly', 'flat', 'cave', 'forest', 'flat',
 'cave', 'hilly', 'cave', 'flat', 'forest', 'forest', 'hilly', 'hilly', 'hilly', 'forest', 'hilly', 'cave',
 'cave', 'flat', 'hilly', 'cave', 'cave', 'flat', 'forest', 'forest', 'flat', 'hilly', 'forest', 'cave', 'cave',],
['flat', 'forest', 'cave', 'cave', 'hilly', 'forest', 'cave', 'flat', 'flat', 'cave', 'cave', 'hilly', 'flat',
 'hilly', 'flat', 'forest', 'cave', 'cave', 'forest', 'cave', 'cave', 'forest', 'flat', 'flat', 'cave', 'forest',
 'flat', 'hilly', 'cave', 'cave', 'forest', 'cave', 'hilly', 'hilly', 'forest', 'forest', 'hilly', 'flat',
 'flat', 'cave', 'forest', 'forest', 'flat', 'hilly', 'hilly', 'forest', 'flat', 'flat', 'hilly', 'flat',],
['hilly', 'forest', 'cave', 'flat', 'hilly', 'flat', 'forest', 'forest', 'flat', 'hilly', 'cave', 'forest',
 'forest', 'flat', 'cave', 'cave', 'flat', 'forest', 'hilly', 'cave', 'cave', 'cave', 'hilly', 'cave', 'cave',
 'flat', 'hilly', 'forest', 'flat', 'hilly', 'flat', 'hilly', 'cave', 'cave', 'forest', 'forest', 'forest',
 'forest', 'forest', 'flat', 'forest', 'cave', 'hilly', 'hilly', 'forest', 'cave', 'forest', 'flat', 'hilly',
 'hilly',],
['flat', 'forest', 'flat', 'hilly', 'flat', 'cave', 'cave', 'flat', 'cave', 'cave', 'hilly', 'cave', 'forest',
 'cave', 'flat', 'hilly', 'cave', 'flat', 'flat', 'forest', 'flat', 'hilly', 'forest', 'forest', 'flat', 'cave',
 'forest', 'hilly', 'cave', 'flat', 'flat', 'flat', 'flat', 'hilly', 'hilly', 'hilly', 'flat', 'flat', 'hilly',
 'cave', 'flat', 'hilly', 'flat', 'hilly', 'hilly', 'hilly', 'hilly', 'flat', 'forest', 'cave',],
['flat', 'cave', 'cave', 'hilly', 'hilly', 'hilly', 'flat', 'forest', 'forest', 'forest', 'flat', 'flat', 'flat',
 'hilly', 'hilly', 'flat', 'flat', 'forest', 'flat', 'cave', 'hilly', 'hilly', 'hilly', 'flat', 'hilly', 'flat',
 'flat', 'forest', 'hilly', 'cave', 'flat', 'flat', 'hilly', 'flat', 'flat', 'forest', 'cave', 'cave', 'forest',
 'hilly', 'hilly', 'forest', 'cave', 'cave', 'forest', 'flat', 'cave', 'hilly', 'hilly', 'cave',],
['flat', 'cave', 'hilly', 'forest', 'hilly', 'hilly', 'hilly', 'forest', 'cave', 'forest', 'flat', 'flat',
 'hilly', 'forest', 'forest', 'cave', 'cave', 'forest', 'cave', 'cave', 'cave', 'forest', 'hilly', 'hilly',
 'cave', 'flat', 'hilly', 'cave', 'hilly', 'cave', 'cave', 'hilly', 'hilly', 'flat', 'cave', 'flat', 'forest',
 'flat', 'flat', 'cave', 'hilly', 'cave', 'cave', 'forest', 'flat', 'cave', 'forest', 'cave', 'cave', 'forest',],
['cave', 'cave', 'forest', 'cave', 'cave', 'hilly', 'forest', 'flat', 'hilly', 'cave', 'flat', 'cave', 'cave',
 'flat', 'cave', 'flat', 'cave', 'flat', 'forest', 'cave', 'cave', 'hilly', 'hilly', 'flat', 'hilly', 'forest',
 'flat', 'cave', 'cave', 'flat', 'hilly', 'hilly', 'hilly', 'cave', 'hilly', 'cave', 'cave', 'cave', 'flat',
 'hilly', 'hilly', 'flat', 'hilly', 'flat', 'flat', 'flat', 'hilly', 'forest', 'cave', 'cave',],
['cave', 'flat', 'cave', 'cave', 'forest', 'forest', 'hilly', 'flat', 'cave', 'cave', 'hilly', 'hilly', 'flat',
 'flat', 'cave', 'forest', 'cave', 'forest', 'forest', 'hilly', 'cave', 'forest', 'hilly', 'forest', 'hilly',
 'flat', 'cave', 'hilly', 'forest', 'cave', 'cave', 'hilly', 'forest', 'cave', 'flat', 'forest', 'forest',
 'flat', 'flat', 'hilly', 'hilly', 'cave', 'forest', 'hilly', 'forest', 'flat', 'hilly', 'forest', 'cave',
 'flat',],
['flat', 'cave', 'forest', 'cave', 'cave', 'flat', 'hilly', 'hilly', 'hilly', 'forest', 'hilly', 'forest',
 'cave', 'forest', 'cave', 'hilly', 'forest', 'cave', 'forest', 'hilly', 'flat', 'cave', 'forest', 'forest',
 'cave', 'forest', 'forest', 'cave', 'hilly', 'forest', 'hilly', 'forest', 'cave', 'cave', 'hilly', 'flat',
 'flat', 'forest', 'flat', 'forest', 'hilly', 'hilly', 'hilly', 'flat', 'forest', 'cave', 'forest', 'cave',
 'flat', 'cave',],
['flat', 'cave', 'flat', 'hilly', 'forest', 'flat', 'forest', 'hilly', 'flat', 'flat', 'cave', 'hilly', 'hilly',
 'hilly', 'flat', 'cave', 'cave', 'cave', 'cave', 'flat', 'cave', 'cave', 'forest', 'forest', 'hilly', 'forest',
 'hilly', 'forest', 'forest', 'cave', 'flat', 'flat', 'forest', 'flat', 'cave', 'hilly', 'cave', 'flat', 'flat',
 'forest', 'hilly', 'forest', 'cave', 'forest', 'forest', 'flat', 'flat', 'forest', 'cave', 'flat',],
['forest', 'cave', 'flat', 'flat', 'flat', 'cave', 'cave', 'forest', 'forest', 'flat', 'forest', 'flat', 'cave',
 'cave', 'forest', 'cave', 'flat', 'hilly', 'forest', 'flat', 'hilly', 'cave', 'cave', 'flat', 'hilly', 'cave',
 'hilly', 'cave', 'forest', 'hilly', 'flat', 'hilly', 'flat', 'cave', 'flat', 'forest', 'cave', 'hilly',
 'forest', 'forest', 'forest', 'hilly', 'cave', 'flat', 'hilly', 'hilly', 'flat', 'flat', 'cave', 'cave',],
['hilly', 'hilly', 'forest', 'hilly', 'hilly', 'forest', 'hilly', 'flat', 'hilly', 'hilly', 'cave', 'forest',
 'hilly', 'forest', 'forest', 'forest', 'forest', 'hilly', 'cave', 'forest', 'hilly', 'cave', 'flat', 'flat',
 'hilly', 'flat', 'flat', 'cave', 'forest', 'flat', 'forest', 'flat', 'hilly', 'flat', 'flat', 'forest', 'cave',
 'forest', 'flat', 'flat', 'hilly', 'cave', 'forest', 'cave', 'flat', 'hilly', 'hilly', 'flat', 'hilly',
 'forest',],
['hilly', 'flat', 'flat', 'cave', 'hilly', 'flat', 'flat', 'flat', 'flat', 'forest', 'forest', 'forest', 'flat',
 'flat', 'hilly', 'cave', 'forest', 'hilly', 'cave', 'flat', 'forest', 'flat', 'forest', 'flat', 'flat', 'cave',
 'flat', 'cave', 'flat', 'cave', 'hilly', 'hilly', 'hilly', 'cave', 'flat', 'cave', 'flat', 'flat', 'hilly',
 'hilly', 'forest', 'flat', 'hilly', 'cave', 'forest', 'forest', 'flat', 'forest', 'forest', 'hilly',],
['flat', 'flat', 'flat', 'hilly', 'forest', 'hilly', 'cave', 'cave', 'cave', 'hilly', 'hilly', 'cave', 'hilly',
 'cave', 'flat', 'forest', 'forest', 'forest', 'hilly', 'forest', 'forest', 'forest', 'cave', 'forest',
 'forest', 'flat', 'forest', 'flat', 'cave', 'flat', 'cave', 'forest', 'hilly', 'forest', 'forest', 'cave',
 'cave', 'cave', 'cave', 'forest', 'cave', 'cave', 'hilly', 'flat', 'forest', 'flat', 'forest', 'hilly', 'hilly',
 'hilly',],
['flat', 'forest', 'hilly', 'cave', 'forest', 'cave', 'forest', 'hilly', 'flat', 'flat', 'hilly', 'hilly',
 'forest', 'flat', 'cave', 'forest', 'hilly', 'flat', 'forest', 'forest', 'flat', 'hilly', 'flat', 'forest',
 'cave', 'forest', 'hilly', 'flat', 'hilly', 'flat', 'flat', 'forest', 'cave', 'cave', 'hilly', 'forest',
 'forest', 'hilly', 'forest', 'forest', 'cave', 'flat', 'forest', 'hilly', 'hilly', 'cave', 'hilly', 'forest',
 'hilly', 'cave',],
['flat', 'flat', 'flat', 'hilly', 'hilly', 'hilly', 'flat', 'cave', 'cave', 'flat', 'forest', 'hilly', 'cave',
 'hilly', 'forest', 'forest', 'forest', 'forest', 'hilly', 'flat', 'flat', 'forest', 'hilly', 'hilly', 'flat',
 'flat', 'forest', 'flat', 'hilly', 'cave', 'forest', 'cave', 'flat', 'hilly', 'cave', 'hilly', 'cave', 'cave',
 'flat', 'forest', 'flat', 'forest', 'hilly', 'cave', 'cave', 'flat', 'flat', 'forest', 'cave', 'hilly',],
['cave', 'flat', 'cave', 'cave', 'hilly', 'hilly', 'hilly', 'cave', 'flat', 'cave', 'forest', 'cave', 'flat',
 'flat', 'forest', 'cave', 'forest', 'hilly', 'cave', 'hilly', 'flat', 'forest', 'cave', 'cave', 'hilly',
 'hilly', 'cave', 'hilly', 'flat', 'cave', 'cave', 'flat', 'hilly', 'flat', 'flat', 'forest', 'cave', 'flat',
 'flat', 'flat', 'forest', 'forest', 'forest', 'forest', 'cave', 'forest', 'cave', 'cave', 'flat', 'forest',],
['cave', 'flat', 'forest', 'forest', 'hilly', 'forest', 'forest', 'flat', 'forest', 'hilly', 'flat', 'cave',
 'flat', 'forest', 'flat', 'cave', 'hilly', 'cave', 'forest', 'flat', 'hilly', 'cave', 'forest', 'forest',
 'flat', 'cave', 'flat', 'flat', 'cave', 'cave', 'forest', 'hilly', 'flat', 'forest', 'forest', 'forest',
 'hilly', 'hilly', 'forest', 'cave', 'flat', 'hilly', 'hilly', 'forest', 'forest', 'forest', 'flat', 'flat',
 'forest', 'forest',],
['flat', 'forest', 'cave', 'flat', 'cave', 'flat', 'cave', 'flat', 'forest', 'flat', 'flat', 'forest', 'flat',
 'flat', 'flat', 'flat', 'forest', 'flat', 'hilly', 'hilly', 'hilly', 'flat', 'forest', 'flat', 'flat', 'forest',
 'forest', 'hilly', 'hilly', 'cave', 'hilly', 'cave', 'flat', 'forest', 'hilly', 'cave', 'hilly', 'forest',
 'cave', 'hilly', 'cave', 'hilly', 'flat', 'flat', 'cave', 'forest', 'forest', 'hilly', 'cave', 'flat',],
['cave', 'hilly', 'cave', 'hilly', 'cave', 'hilly', 'forest', 'hilly', 'cave', 'forest', 'cave', 'forest',
 'flat', 'forest', 'cave', 'flat', 'hilly', 'hilly', 'hilly', 'forest', 'hilly', 'cave', 'cave', 'flat', 'cave',
 'hilly', 'forest', 'cave', 'hilly', 'hilly', 'forest', 'cave', 'hilly', 'cave', 'hilly', 'forest', 'hilly',
 'hilly', 'hilly', 'forest', 'flat', 'hilly', 'flat', 'hilly', 'cave', 'cave', 'flat', 'cave', 'hilly', 'hilly',],
['forest', 'flat', 'cave', 'hilly', 'hilly', 'cave', 'hilly', 'hilly', 'forest', 'forest', 'hilly', 'flat',
 'hilly', 'forest', 'forest', 'flat', 'flat', 'hilly', 'hilly', 'forest', 'flat', 'hilly', 'flat', 'hilly',
 'cave', 'cave', 'cave', 'hilly', 'flat', 'hilly', 'forest', 'hilly', 'cave', 'cave', 'hilly', 'hilly', 'hilly',
 'flat', 'hilly', 'hilly', 'forest', 'cave', 'flat', 'hilly', 'hilly', 'hilly', 'forest', 'forest', 'hilly',
 'hilly',],
['forest', 'forest', 'flat', 'cave', 'forest', 'flat', 'forest', 'flat', 'forest', 'flat', 'flat', 'forest',
 'forest', 'forest', 'cave', 'cave', 'cave', 'forest', 'forest', 'cave', 'cave', 'cave', 'hilly', 'flat',
 'hilly', 'flat', 'hilly', 'cave', 'flat', 'forest', 'flat', 'cave', 'forest', 'hilly', 'cave', 'cave', 'cave',
 'cave', 'hilly', 'cave', 'hilly', 'flat', 'forest', 'cave', 'flat', 'hilly', 'hilly', 'forest', 'cave', 'hilly',],
['hilly', 'forest', 'cave', 'hilly', 'flat', 'flat', 'cave', 'flat', 'flat', 'flat', 'cave', 'forest', 'cave',
 'flat', 'hilly', 'forest', 'forest', 'flat', 'hilly', 'forest', 'hilly', 'hilly', 'cave', 'forest', 'forest',
 'hilly', 'forest', 'forest', 'hilly', 'hilly', 'flat', 'cave', 'cave', 'hilly', 'cave', 'hilly', 'cave',
 'forest', 'forest', 'cave', 'cave', 'hilly', 'forest', 'forest', 'flat', 'forest', 'hilly', 'flat', 'forest',
 'hilly',],
['hilly', 'hilly', 'cave', 'cave', 'forest', 'cave', 'flat', 'cave', 'cave', 'flat', 'flat', 'cave', 'flat',
 'forest', 'forest', 'hilly', 'cave', 'cave', 'cave', 'hilly', 'hilly', 'flat', 'cave', 'forest', 'cave', 'cave',
 'hilly', 'cave', 'forest', 'flat', 'hilly', 'cave', 'forest', 'cave', 'flat', 'cave', 'cave', 'forest', 'cave',
 'flat', 'hilly', 'cave', 'flat', 'hilly', 'forest', 'flat', 'flat', 'cave', 'hilly', 'cave',],
['hilly', 'cave', 'flat', 'flat', 'hilly', 'cave', 'forest', 'hilly', 'hilly', 'forest', 'forest', 'cave',
 'hilly', 'forest', 'cave', 'flat', 'cave', 'cave', 'flat', 'hilly', 'flat', 'flat', 'cave', 'hilly', 'cave',
 'hilly', 'cave', 'cave', 'cave', 'cave', 'hilly', 'cave', 'hilly', 'cave', 'forest', 'cave', 'cave', 'flat',
 'cave', 'forest', 'cave', 'cave', 'hilly', 'forest', 'forest', 'flat', 'forest', 'cave', 'forest', 'flat',],
['cave', 'cave', 'hilly', 'cave', 'forest', 'flat', 'cave', 'cave', 'forest', 'flat', 'hilly', 'cave', 'cave',
 'hilly', 'flat', 'forest', 'forest', 'hilly', 'flat', 'hilly', 'flat', 'hilly', 'hilly', 'forest', 'forest',
 'flat', 'flat', 'forest', 'flat', 'cave', 'flat', 'flat', 'forest', 'cave', 'forest', 'hilly', 'flat', 'forest',
 'flat', 'cave', 'hilly', 'cave', 'forest', 'forest', 'flat', 'forest', 'forest', 'cave', 'forest', 'flat',],
['hilly', 'flat', 'forest', 'flat', 'cave', 'flat', 'forest', 'flat', 'cave', 'hilly', 'cave', 'hilly', 'forest',
 'flat', 'forest', 'flat', 'flat', 'hilly', 'hilly', 'cave', 'flat', 'cave', 'cave', 'forest', 'hilly', 'flat',
 'cave', 'hilly', 'flat', 'cave', 'flat', 'flat', 'flat', 'cave', 'cave', 'cave', 'forest', 'hilly', 'flat',
 'hilly', 'hilly', 'forest', 'flat', 'hilly', 'cave', 'forest', 'flat', 'hilly', 'forest', 'cave',],
['flat', 'hilly', 'hilly', 'cave', 'cave', 'flat', 'cave', 'cave', 'forest', 'hilly', 'forest', 'flat', 'forest',
 'forest', 'forest', 'hilly', 'flat', 'flat', 'flat', 'cave', 'hilly', 'hilly', 'forest', 'flat', 'cave',
 'hilly', 'hilly', 'cave', 'forest', 'flat', 'cave', 'cave', 'cave', 'cave', 'forest', 'flat', 'flat', 'flat',
 'hilly', 'cave', 'cave', 'forest', 'hilly', 'flat', 'flat', 'hilly', 'forest', 'forest', 'cave', 'flat',],
['forest', 'hilly', 'hilly', 'forest', 'hilly', 'forest', 'forest', 'forest', 'cave', 'flat', 'forest',
 'hilly', 'cave', 'hilly', 'forest', 'forest', 'flat', 'flat', 'forest', 'forest', 'flat', 'flat', 'cave',
 'hilly', 'hilly', 'cave', 'forest', 'forest', 'forest', 'cave', 'cave', 'flat', 'hilly', 'cave', 'cave',
 'hilly', 'forest', 'forest', 'forest', 'cave', 'cave', 'forest', 'flat', 'flat', 'flat', 'flat', 'cave',
 'hilly', 'flat', 'cave',],
['cave', 'forest', 'flat', 'hilly', 'forest', 'flat', 'flat', 'forest', 'hilly', 'forest', 'cave', 'flat',
 'cave', 'forest', 'forest', 'forest', 'cave', 'cave', 'forest', 'cave', 'flat', 'hilly', 'cave', 'forest',
 'flat', 'cave', 'hilly', 'forest', 'cave', 'cave', 'cave', 'flat', 'cave', 'forest', 'cave', 'forest', 'forest',
 'hilly', 'flat', 'forest', 'flat', 'flat', 'cave', 'flat', 'forest', 'forest', 'flat', 'forest', 'hilly',
 'cave',],
['forest', 'flat', 'hilly', 'cave', 'forest', 'cave', 'forest', 'cave', 'hilly', 'forest', 'cave', 'hilly',
 'cave', 'hilly', 'cave', 'forest', 'flat', 'flat', 'hilly', 'hilly', 'cave', 'cave', 'cave', 'flat', 'flat',
 'hilly', 'flat', 'hilly', 'hilly', 'cave', 'hilly', 'forest', 'cave', 'hilly', 'cave', 'flat', 'forest',
 'hilly', 'hilly', 'forest', 'hilly', 'flat', 'hilly', 'cave', 'cave', 'cave', 'flat', 'hilly', 'cave', 'cave',],
['flat', 'forest', 'flat', 'hilly', 'hilly', 'hilly', 'forest', 'forest', 'hilly', 'flat', 'flat', 'flat',
 'hilly', 'forest', 'flat', 'flat', 'flat', 'flat', 'forest', 'flat', 'forest', 'forest', 'flat', 'flat', 'flat',
 'hilly', 'hilly', 'flat', 'cave', 'forest', 'cave', 'cave', 'hilly', 'flat', 'forest', 'cave', 'flat', 'flat',
 'hilly', 'hilly', 'hilly', 'flat', 'flat', 'flat', 'flat', 'forest', 'forest', 'flat', 'cave', 'cave',],
['flat', 'hilly', 'flat', 'cave', 'cave', 'forest', 'flat', 'cave', 'forest', 'hilly', 'forest', 'cave', 'flat',
 'flat', 'forest', 'hilly', 'flat', 'cave', 'cave', 'forest', 'forest', 'cave', 'flat', 'hilly', 'cave', 'hilly',
 'forest', 'hilly', 'cave', 'forest', 'forest', 'flat', 'flat', 'flat', 'cave', 'hilly', 'hilly', 'flat', 'cave',
 'flat', 'flat', 'forest', 'hilly', 'forest', 'cave', 'flat', 'hilly', 'hilly', 'flat', 'hilly',],
['forest', 'cave', 'forest', 'cave', 'forest', 'forest', 'flat', 'forest', 'flat', 'flat', 'forest', 'cave',
 'flat', 'forest', 'forest', 'hilly', 'forest', 'cave', 'flat', 'hilly', 'forest', 'flat', 'flat', 'hilly',
 'forest', 'cave', 'hilly', 'cave', 'flat', 'flat', 'cave', 'hilly', 'flat', 'hilly', 'forest', 'forest',
 'forest', 'cave', 'forest', 'forest', 'hilly', 'hilly', 'cave', 'cave', 'forest', 'flat', 'cave', 'cave',
 'forest', 'forest',],
['forest', 'cave', 'cave', 'cave', 'hilly', 'hilly', 'forest', 'hilly', 'cave', 'forest', 'cave', 'forest',
 'hilly', 'hilly', 'cave', 'flat', 'cave', 'hilly', 'cave', 'cave', 'forest', 'forest', 'hilly', 'flat', 'flat',
 'hilly', 'flat', 'flat', 'flat', 'flat', 'forest', 'flat', 'hilly', 'cave', 'hilly', 'hilly', 'flat', 'flat',
 'flat', 'flat', 'forest', 'forest', 'forest', 'hilly', 'hilly', 'forest', 'hilly', 'forest', 'flat', 'flat',],
['forest', 'cave', 'flat', 'flat', 'hilly', 'flat', 'hilly', 'hilly', 'cave', 'cave', 'hilly', 'cave', 'hilly',
 'flat', 'forest', 'flat', 'cave', 'cave', 'hilly', 'flat', 'cave', 'cave', 'flat', 'hilly', 'flat', 'flat', 'flat',
 'hilly', 'forest', 'forest', 'forest', 'hilly', 'cave', 'hilly', 'cave', 'flat', 'flat', 'cave', 'cave',
 'hilly', 'hilly', 'cave', 'cave', 'forest', 'flat', 'cave', 'cave', 'flat', 'forest', 'cave',],
['forest', 'cave', 'flat', 'cave', 'hilly', 'flat', 'hilly', 'cave', 'forest', 'forest', 'forest', 'hilly',
 'cave', 'cave', 'hilly', 'hilly', 'flat', 'flat', 'cave', 'forest', 'flat', 'flat', 'cave', 'cave', 'forest',
 'cave', 'hilly', 'flat', 'flat', 'cave', 'cave', 'cave', 'forest', 'hilly', 'cave', 'hilly', 'flat', 'forest',
 'cave', 'cave', 'forest', 'hilly', 'hilly', 'forest', 'hilly', 'cave', 'flat', 'cave', 'forest', 'cave',],
['forest', 'flat', 'flat', 'hilly', 'hilly', 'hilly', 'forest', 'flat', 'hilly', 'flat', 'forest', 'forest',
 'forest', 'cave', 'cave', 'hilly', 'cave', 'forest', 'flat', 'cave', 'forest', 'cave', 'cave', 'forest', 'cave',
 'forest', 'cave', 'forest', 'flat', 'cave', 'hilly', 'flat', 'forest', 'forest', 'cave', 'hilly', 'forest',
 'cave', 'hilly', 'forest', 'flat', 'hilly', 'hilly', 'flat', 'forest', 'forest', 'forest', 'flat', 'flat',
 'cave',],
['hilly', 'hilly', 'flat', 'forest', 'hilly', 'cave', 'forest', 'flat', 'hilly', 'flat', 'forest', 'forest',
 'forest', 'hilly', 'hilly', 'forest', 'flat', 'forest', 'hilly', 'flat', 'cave', 'flat', 'flat', 'cave', 'cave',
 'hilly', 'flat', 'hilly', 'cave', 'cave', 'cave', 'forest', 'cave', 'hilly', 'cave', 'forest', 'forest',
 'hilly', 'forest', 'flat', 'cave', 'forest', 'flat', 'forest', 'forest', 'forest', 'forest', 'hilly', 'flat',
 'cave',],
['hilly', 'hilly', 'flat', 'flat', 'forest', 'hilly', 'flat', 'forest', 'cave', 'flat', 'hilly', 'forest',
 'hilly', 'forest', 'flat', 'flat', 'flat', 'forest', 'forest', 'cave', 'forest', 'flat', 'cave', 'cave',
 'forest', 'cave', 'cave', 'forest', 'hilly', 'forest', 'forest', 'forest', 'hilly', 'forest', 'hilly',
 'cave', 'flat', 'cave', 'cave', 'flat', 'flat', 'hilly', 'cave', 'forest', 'cave', 'cave', 'forest', 'cave',
 'hilly', 'forest',],
['forest', 'hilly', 'forest', 'forest', 'cave', 'hilly', 'hilly', 'forest', 'hilly', 'flat', 'cave', 'cave',
 'forest', 'forest', 'forest', 'cave', 'hilly', 'flat', 'hilly', 'hilly', 'hilly', 'cave', 'forest', 'flat',
 'cave', 'hilly', 'flat', 'hilly', 'hilly', 'forest', 'flat', 'forest', 'flat', 'flat', 'forest', 'hilly',
 'flat', 'cave', 'cave', 'forest', 'cave', 'flat', 'forest', 'hilly', 'flat', 'hilly', 'flat', 'flat', 'flat',
 'cave',],
['hilly', 'cave', 'hilly', 'cave', 'hilly', 'hilly', 'forest', 'flat', 'flat', 'hilly', 'hilly', 'flat', 'hilly',
 'forest', 'cave', 'hilly', 'hilly', 'flat', 'forest', 'hilly', 'cave', 'flat', 'hilly', 'flat', 'flat',
 'forest', 'forest', 'forest', 'hilly', 'hilly', 'hilly', 'flat', 'flat', 'flat', 'hilly', 'cave', 'flat',
 'flat', 'cave', 'forest', 'forest', 'flat', 'hilly', 'flat', 'flat', 'forest', 'hilly', 'flat', 'cave', 'flat',],
['cave', 'flat', 'hilly', 'flat', 'flat', 'hilly', 'hilly', 'flat', 'hilly', 'cave', 'flat', 'hilly', 'cave',
 'cave', 'hilly', 'hilly', 'flat', 'forest', 'hilly', 'forest', 'forest', 'flat', 'forest', 'forest',
 'forest', 'forest', 'forest', 'forest', 'cave', 'cave', 'cave', 'forest', 'cave', 'flat', 'forest', 'cave',
 'forest', 'hilly', 'flat', 'forest', 'flat', 'flat', 'hilly', 'cave', 'cave', 'cave', 'forest', 'forest',
 'flat', 'flat',],
['flat', 'hilly', 'hilly', 'cave', 'forest', 'cave', 'forest', 'hilly', 'hilly', 'flat', 'flat', 'cave', 'hilly',
 'cave', 'cave', 'hilly', 'forest', 'hilly', 'cave', 'forest', 'flat', 'hilly', 'forest', 'forest', 'cave',
 'flat', 'cave', 'hilly', 'cave', 'forest', 'cave', 'cave', 'forest', 'forest', 'hilly', 'hilly', 'hilly',
 'hilly', 'cave', 'hilly', 'hilly', 'cave', 'flat', 'flat', 'flat', 'forest', 'hilly', 'flat', 'hilly', 'forest',],
['hilly', 'hilly', 'forest', 'flat', 'hilly', 'hilly', 'flat', 'cave', 'flat', 'hilly', 'forest', 'flat', 'flat',
 'forest', 'hilly', 'forest', 'forest', 'hilly', 'forest', 'cave', 'cave', 'cave', 'forest', 'flat', 'hilly',
 'hilly', 'forest', 'forest', 'flat', 'hilly', 'flat', 'cave', 'cave', 'forest', 'flat', 'flat', 'cave', 'cave',
 'cave', 'cave', 'forest', 'forest', 'cave', 'flat', 'forest', 'hilly', 'cave', 'cave', 'cave', 'cave',],
['forest', 'flat', 'hilly', 'hilly', 'flat', 'hilly', 'hilly', 'forest', 'hilly', 'hilly', 'flat', 'flat',
 'flat', 'forest', 'forest', 'cave', 'hilly', 'hilly', 'forest', 'cave', 'hilly', 'cave', 'forest', 'hilly',
 'forest', 'hilly', 'flat', 'flat', 'flat', 'flat', 'hilly', 'forest', 'cave', 'flat', 'hilly', 'forest', 'flat',
 'flat', 'flat', 'forest', 'cave', 'flat', 'cave', 'flat', 'cave', 'forest', 'hilly', 'forest', 'cave', 'flat',],
['hilly', 'forest', 'forest', 'hilly', 'cave', 'hilly', 'hilly', 'forest', 'cave', 'flat', 'cave', 'forest',
 'forest', 'cave', 'flat', 'forest', 'cave', 'hilly', 'flat', 'hilly', 'forest', 'flat', 'cave', 'hilly',
 'hilly', 'cave', 'flat', 'hilly', 'forest', 'flat', 'hilly', 'hilly', 'flat', 'hilly', 'cave', 'hilly', 'flat',
 'forest', 'forest', 'cave', 'forest', 'forest', 'forest', 'hilly', 'flat', 'cave', 'hilly', 'cave', 'forest',
 'hilly',],
['cave', 'hilly', 'forest', 'flat', 'forest', 'hilly', 'forest', 'cave', 'hilly', 'hilly', 'cave', 'forest',
 'flat', 'forest', 'forest', 'cave', 'hilly', 'hilly', 'hilly', 'cave', 'cave', 'forest', 'forest', 'cave',
 'cave', 'hilly', 'cave', 'forest', 'hilly', 'cave', 'forest', 'forest', 'forest', 'cave', 'hilly', 'hilly',
 'forest', 'hilly', 'cave', 'forest', 'cave', 'cave', 'forest', 'cave', 'hilly', 'hilly', 'cave', 'forest',
 'hilly', 'cave',],
['cave', 'cave', 'cave', 'hilly', 'cave', 'cave', 'hilly', 'cave', 'cave', 'cave', 'cave', 'cave', 'forest',
 'hilly', 'hilly', 'hilly', 'hilly', 'cave', 'hilly', 'hilly', 'forest', 'hilly', 'cave', 'hilly', 'hilly',
 'hilly', 'cave', 'cave', 'hilly', 'hilly', 'hilly', 'cave', 'hilly', 'cave', 'cave', 'hilly', 'cave', 'cave',
 'cave', 'cave', 'cave', 'hilly', 'cave', 'cave', 'cave', 'hilly', 'cave', 'cave', 'hilly', 'hilly',],
['cave', 'cave', 'cave', 'hilly', 'hilly', 'hilly', 'hilly', 'hilly', 'cave', 'cave', 'hilly', 'hilly', 'hilly',
 'cave', 'cave', 'hilly', 'hilly', 'cave', 'cave', 'cave', 'cave', 'hilly', 'cave', 'cave', 'hilly', 'hilly',
 'hilly', 'hilly', 'hilly', 'hilly', 'hilly', 'hilly', 'hilly', 'hilly', 'hilly', 'hilly', 'hilly', 'hilly',
 'hilly', 'hilly', 'hilly', 'hilly', 'hilly', 'hilly', 'hilly', 'hilly', 'hilly', 'hilly', 'hilly', 'hilly',]]
